config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  scope do
    resources :portfolios, path: 'portfolio'
    resources :interests, path: 'research'
    resources :resumes, path: 'cv'
    resources :backgrounds, path: 'about'
  end

  resources :resources


  # static pages routes
  get 'oldabout' => 'static_pages#about'
  get 'edit' => 'static_pages#edit'
  get 'editresources' => 'static_pages#editresources'
  get 'home' => 'static_pages#home'
  get 'freelance' => 'static_pages#freelance'
  get 'shop' => 'static_pages#shop'
  get 'login' => 'devise/sessions#new'
  get 'logout' => 'devise/sessions#destroy'

end

app/models/background.rb
class Background < ActiveRecord::Base
end

app/models/interest.rb
class Interest < ActiveRecord::Base
end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
	mount_uploader :image, ImageUploader

	extend FriendlyId
  	friendly_id :title, use: :slugged
end

app/models/resource.rb
class Resource < ActiveRecord::Base
	mount_uploader :document, DocumentUploader
	validates :title, presence: true
end

app/models/resume.rb
class Resume < ActiveRecord::Base
	mount_uploader :attachment, AttachmentUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/backgrounds_controller.rb
class BackgroundsController < ApplicationController
	def index
		@background = Background.first
	end

	def new
		@background = Background.new
	end

	def create
		@background = Background.new(background_params)
		if @background.update_attributes(background_params)
			redirect_to action: 'index'
		else
			render 'new'
		end
	end

	def edit
		@background = Background.find(params[:id])
	end

	def update
		@background = Background.find(params[:id])
		if @background.update_attributes(background_params)
			redirect_to action: 'index'
		else
			render 'edit'
		end
	end

	private

	def background_params
		params.require(:background).permit(:about, :contact)
	end
end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController
	def index
		@resume = Resume.first
		@resumes = Resume.all
		@interest = Interest.first
		
		@education = Resource.where(:category => 'Education')
		@interviews = Resource.where(:category => 'Interviews')
		@media = Resource.where(:category => 'Media')
	end

	def new
		@interest = Interest.new
	end

	def create
		@interest = Interest.new(interest_params)
		if @interest.update_attributes(interest_params)
			redirect_to action: 'index'
		else 
			render 'new'
		end
	end

	def edit
		@interest = Interest.find(params[:id])
	end

	def update
		@interest = Interest.find(params[:id])
		if @interest.update_attributes(interest_params)
			redirect_to action: 'index'
		else 
			render 'edit'
		end
	end

	private

	def interest_params
		params.require(:interest).permit(:topics, :positions)
	end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
	def index
		@images = Portfolio.order(created_at: :desc)
	end
	
	def new
		@image = Portfolio.new
	end

	def create
		@image = Portfolio.new(image_params)
		if @image.update_attributes(image_params)
			redirect_to @image
		else 
			render 'new'
		end
	end

	def destroy
		@image = Portfolio.friendly.find(params[:id])
		@image.destroy
		redirect_to root_path
	end

	def edit
		@image = Portfolio.friendly.find(params[:id])
	end

	def update
		@image = Portfolio.friendly.find(params[:id])
		if @image.update_attributes(image_params)
			redirect_to @image
		else
			render 'edit'
		end
	end

	def show
		@image = Portfolio.friendly.find(params[:id])
	end

	private

	def image_params
		params.require(:portfolio).permit(:title, :image, :description, :category, :price, :medium, :dimensions)
	end
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
	def new
		@resource = Resource.new
	end

	def create
		@resource = Resource.new(resource_params)
		if @resource.save
      		redirect_to interests_path
    	else
      		render "new"
    	end
	end

	def edit
		@resource = Resource.find(params[:id])
	end

	def update
		@resource = Resource.find(params[:id])
    	if @resource.update_attributes(resource_params)
      		redirect_to editresources_path
    	else 
      		render 'edit'
    	end
	end

	def destroy
    	@resource = Resource.find(params[:id])
    	@resource.destroy
    	redirect_to editresources_path
  	end

  	private

  	def resource_params
    	params.require(:resource).permit(:title, :document, :link, :category, :description)
  	end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  def index
    @resumes = Resume.all
    @resume = Resume.last
  end

  def new
    @resume = Resume.new
  end

  def create
    @resume = Resume.new(resume_params)

    if @resume.save
      redirect_to interests_path
    else
      render "new"
    end
  end

  def edit
    @resume = Resume.find(params[:id])
  end

  def update
    @resume = Resume.find(params[:id])
    if @resume.update_attributes(resume_params)
      redirect_to interests_path
    else 
      render 'edit'
    end
  end

  def destroy
    @resume = Resume.find(params[:id])
    @resume.destroy
    redirect_to resumes_path
  end

private

  def resume_params
    params.require(:resume).permit(:attachment)
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def shop
		@sales = Portfolio.where(:category => 'For Sale').order(created_at: :desc)
	end

	def freelance
		@freelance = Portfolio.where(:category => 'Freelance').order(created_at: :desc)
	end

	def edit
		@interest = Interest.last
		@interests = Interest.all
		@background = Background.last
		@backgrounds = Background.all
	end

	def editresources
		@resources = Resource.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def cp(path)
  		"active-nav" if current_page?(path)
	end

	def full_title(page_title = '')
    	base_title = "David Bonan"
	    if page_title.empty?
	      base_title
	    else
	      page_title + ' | ' + base_title
	    end
  	end
end

app/helpers/backgrounds_helper.rb
module BackgroundsHelper
end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/backgrounds/_form.html.erb
<div class = "blog-form-container">
<%= form_for @background do |b| %>
    <p>
    <%= b.label :About %><br />
    <div data-no-turbolink><%= b.text_area :about, :class => 'ckeditor'  %></div>
  </p>

  <p>
    <%= b.label :Contact %><br />
    <div data-no-turbolink><%= b.text_area :contact, :class => 'ckeditor'  %></div>
  </p>

  <p><%= b.submit "Update"%></p>

<% end %>
</div>

app/views/backgrounds/edit.html.erb
<% provide(:title, 'About & Contact') %>

<h1 class = 'research-title'>Edit Background Information</h1>
<%= render partial: 'form' %>

app/views/backgrounds/index.html.erb
<% provide(:title, 'About') %>
<div class = "about-image-container">
	<div class = "about-image">
		
	</div>
</div>

<div class = "about-text-container">
	<div class = "background-description">
		<p id = "research-headings">About</p>
		<p><%= @background.about.html_safe %></p>
	</div>

	<div class = "background-description">
		<p id = "research-headings">Contact</p>
		<p><%= @background.contact.html_safe %></p>
	</div>

</div>

app/views/backgrounds/new.html.erb
<% provide(:title, 'About & Contact') %>

<h1 class = 'research-title'>Add Background Information</h1>
<%= render partial: 'form' %>

app/views/interests/_form.html.erb
<div class = "blog-form-container">
<%= form_for @interest do |i| %>
    <p>
    <%= i.label :Interests %><br />
    <div data-no-turbolink><%= i.text_area :topics, :class => 'ckeditor'  %></div>
  </p>

  <p>
    <%= i.label :positions %><br />
    <div data-no-turbolink><%= i.text_area :positions, :class => 'ckeditor'  %></div>
  </p>

  <p><%= i.submit "Update"%></p>

<% end %>
</div>

app/views/interests/edit.html.erb
<%= render partial: 'form' %>

app/views/interests/index.html.erb
<% provide(:title, 'Research') %>

<h1 class = 'research-title'>Research</h1>

<% if @resumes.count > 0 %> <!-- if there is a resume uploaded -->

<%= link_to (@resume.attachment.url) do %>
		<%= image_tag(("cv-icon.png"), :class => "cv-icon") %>
		<i><p class = 'dimensions' id = 'medium'>Curriculum Vitae</p></i>
<% end %>

<% else %>
<% end %>


<div class = "research-description">
	<p id = "research-headings">Interests</p>
	<p><%= @interest.topics.html_safe %></p>
</div>

<div class = "research-description">
	<p id = "research-headings">Positions</p>
	<p><%= @interest.positions.html_safe %></p>
</div>

<div class = "research-description">
	<p id = "research-headings">Outreach</p>

	<p id = "research-headings-small">Education</p>
	<% for doc in @education do %>
		<p id = "doc-title"><%= doc.title%></p> <p id = "doc-link"> — 
			<% if doc.document? %> 
				<%= link_to "Link", doc.document.url, target: "_blank" %>
			<% else %>
				<%= link_to "Link", doc.link, target: "_blank" %>
			<% end %>
		</p>
		<p id = "outreach-description">
			<%= doc.description %>
		</p>
	<% end %>

	<p id = "research-headings-small">Writing</p>
	<% for doc in @interviews do %>
		<p id = "doc-title"><%= doc.title%></p> <p id = "doc-link"> — 
			<% if doc.document? %> 
				<%= link_to "Link", doc.document.url, target: "_blank" %>
			<% else %>
				<%= link_to "Link", doc.link, target: "_blank" %>
			<% end %>
		</p>
		<p id = "outreach-description">
			<%= doc.description %>
		</p>
	<% end %>

	<p id = "research-headings-small">Media</p>
	<% for doc in @media do %>
		<p id = "doc-title"><%= doc.title%></p> <p id = "doc-link">— 
			<% if doc.document? %> 
				<%= link_to "Link", doc.document.url, target: "_blank" %>
			<% else %>
				<%= link_to "Link", doc.link, target: "_blank" %>
			<% end %>
		</p>
		<p id = "outreach-description">
			<%= doc.description %>
		</p>
	<% end %>
</div>








<% if false %>
<div class = "image-show-description">
	<p id = "research-headings">Interests</p>
	<p><%= @interest.topics.html_safe %></p>
</div>

<div class = "image-show-description">
	<p id = "research-headings">Positions</p>
	<p><%= @interest.positions.html_safe %></p>
</div>

<% end %>

app/views/interests/new.html.erb
<%= render partial: 'form' %>

app/views/layouts/_artheader.html.erb
<div class = "artheader-container">
	<div class = 'artheader-descriptions'>
		<p id = "nav-links">Illustrations  &middot;  Digital  &middot;  Pen & Ink  &middot;  Watercolor</p>
	</div>
</div>
<div class = "artheader-container">
	<div class = 'artheader-nav'>
		<p id = "nav-links"><%= link_to "Freelance", freelance_path, class: cp(freelance_path)%></p>
		<p id = "nav-links"><%= link_to "For Sale", shop_path, class: cp(shop_path)%></p>
	</div>
</div>

app/views/layouts/_footer.html.erb
<div class = "footer-container">
	<div class = "footer-divider"></div>
	<h1 id = "home-text" class = "footer-text">David Bonan</h1>
	<h5 class = "footer-list">Artist • Climber • Scientist</h5>
	<h5 class = "copyright">Site designed by <a href="http://www.tombonan.me" target = "_blank">Tom Bonan</a></h5>
	<div class = "footer-social">
		<p id = "footer-icon"><a href="https://www.instagram.com/david_bonan/" target = "_blank"><i class = "icon" style="background-image: url(<%= asset_path 'icons/instagram.png' %>) ;"></i></a></p>
		<% if false %>
		<p id = "footer-icon"><a href="https://www.facebook.com/david.bonan.71" target = "_blank"><i class = "icon" style="background-image: url(<%= asset_path 'icons/facebook.png' %>) ;"></i></a></p>
		<p id = "footer-icon"><a href="https://www.linkedin.com/in/david-bonan-17240a115" target = "_blank"><i class = "icon" style="background-image: url(<%= asset_path 'icons/linked-in.png' %>) ;"></i></a></p>
		<% end %>
	</div>
</div>

app/views/layouts/_header.html.erb
<div class = "header-container">
	<div class = "home-text">
		<h1 id = "home-text"><%= link_to "David Bonan", root_path %></h1>
	</div>
	<div class = "header-nav">
		<p id = "nav-links"><%= link_to "Art", portfolios_path, class: cp(portfolios_path) %></p>
		<p id = "nav-links"><%= link_to "Science", interests_path, class: cp(interests_path) %></p>
		<p id = "nav-links"><%= link_to "About & Contact", backgrounds_path, class: cp(backgrounds_path) %></p>
		
		<p id = "icons"><a href="https://www.instagram.com/david_bonan/" target = "_blank"><i class = "icon" style="background-image: url(<%= asset_path 'icons/instagram.png' %>) ;"></i></a></p>

	<% if false %>
		<p id = "icons"><a href="https://www.facebook.com/david.bonan.71" target = "_blank"><i class = "icon" style="background-image: url(<%= asset_path 'icons/facebook.png' %>) ;"></i></a></p>
		<p id = "icons"><a href="https://www.linkedin.com/in/david-bonan-17240a115" target = "_blank"><i class = "icon" style="background-image: url(<%= asset_path 'icons/linked-in.png' %>) ;"></i></a></p>
	<% end %>
	</div>

	<div class = "dropdown-menu">
		<p>Menu</p>
		<p><i class = "dropdown-icon" style="background-image: url(<%= asset_path 'icons/menu.png' %>) ;"></i></p>
	</div>
	<div class = "side-menu">
		<ul>
			<li><%= link_to "Art", portfolios_path %></li>
			<li id = "sub-link">— <%= link_to "Freelance", freelance_path %></li>
			<li id = "sub-link">— <%= link_to "For Sale", shop_path %></li>
			<li><%= link_to "Science", interests_path %></li>
			<li><%= link_to "About & Contact", backgrounds_path %></li>
		</ul>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Raleway:300,500' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Playfair+Display' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  	<%= favicon_link_tag 'favicon.png' %>
</head>
<body>
<%= render partial: 'layouts/header' %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>
<%= render partial: 'layouts/footer' %>
</body>
</html>

app/views/portfolios/_form.html.erb
<div class = "blog-form-container">
<%= form_for @image, :html => {:multipart => true} do |f| %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>

  <% if @image.image? %>
  <% else %>
	  <p>
	    <%= f.file_field :image %>
	  </p>
  <% end %>

  <p>
    <%= f.label :category %><br />
    <%= f.select :category, ['None', 'For Sale', 'Freelance']%>
  </p>
  <p>
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </p>
  <p>
    <%= f.label :medium %><br />
    <%= f.text_field :medium %>
  </p>
  <p>
    <%= f.label :dimensions %><br />
    <%= f.text_field :dimensions %>
  </p>

  <p><%= f.submit "Update"%></p>
<% end %>
</div>

app/views/portfolios/edit.html.erb
<%= render partial: 'form' %>

<%= link_to(portfolio_path(@image) , 
          method: :delete , 
       data: {confirm: "Are you sure you want to delete this image?"}, :class => "delete-image") do %>
       <p>Delete Image</p>
<% end %>

app/views/portfolios/index.html.erb
<%= render partial: 'layouts/artheader' %>
<div class = "portfolio-container">
<% for art in @images do %>
	<%= link_to (portfolio_path(art)) do %>
		<div class = "image-block" style="background-image: url('<%= art.image_url(:thumb) %>');">
			<div class = "index-text">
				<h1 class = "index-title"><%= art.title %></h1>
				<div class = "index-divider"></div>
				<p class = "description-preview"><%= truncate(art.description, length: 80, separator: ' ', :escape => false) %></p>
				<div class = "arrow"></div>
			</div>
		</div>
	<% end %>
<% end %>
</div>

app/views/portfolios/show.html.erb
<% provide(:title, "#{@image.title}") %>
<div class = "image-show" style="background-image: url('<%= @image.image_url %>');">
</div>
<div class = "show-container">
<h2 class = "image-show-title"><%= @image.title %></h2>
<% if @image.medium? && @image.dimensions? %>
	<h5 class = "dimensions"><%= @image.dimensions %> | <span id = "medium"><%= @image.medium %></span></h5>
<% end %>

<% if @image.price? %>
	<h5 class = "image-price">$<%= @image.price %></h5>
<% end %>
<p class = "image-show-description"><%= @image.description %></p>
</div>

app/views/resources/_form.html.erb
<div class = "blog-form-container">
	<%= form_for @resource, html: { multipart: true } do |r| %>
	
		
	
      <p>
		  <%= r.label :title %><br>
    	<%= r.text_field :title %>
      </p>
    	
      <p>
        <%= r.label :category %><br />
        <%= r.select :category, ['Education', 'Interviews', 'Media']%>
      </p>

      <p>
      <%= r.label :description %><br>
      <%= r.text_area :description %>
      </p>

      <p>
      <%= r.label :link %><br>
      <%= r.text_field :link %>
      </p>
    	
      <% if @resource.document? %>
      
      <% else %>
      <p>
         <%= r.file_field :document %>
      </p>
      <% end %>

      <p>
    	   <%= r.submit "Update"%>
      </p>
  <% end %>
</div>

app/views/resources/edit.html.erb
<% provide(:title, 'Edit Document') %>

<h1 class = 'research-title'>Edit Resource</h1>
<%= render partial: 'form' %>

app/views/resources/new.html.erb
<% provide(:title, 'Add Document') %>

<h1 class = 'research-title'>Add Document</h1>
<%= render partial: 'form' %>

app/views/resumes/_form.html.erb
<div class = "blog-form-container">
	<%= form_for @resume, html: { multipart: true } do |f| %>
	<% if @resume.attachment? %>
		
	<% else %>
    	<%= f.label :attachment %> <br>
    	<%= f.file_field :attachment %>
    	<%= f.submit "Update"%>
   	<% end %>
  <% end %>
</div>

app/views/resumes/edit.html.erb
<% provide(:title, 'Edit CV') %>

<h1 class = 'research-title'>Edit CV</h1>
<%= render partial: 'form' %>

app/views/resumes/index.html.erb
<% provide(:title, 'CV') %>

<h1 class = 'research-title'>CV Upload</h1>

<% if @resumes.count > 0 %> <!-- if there is a resume -->
	<div class = "image-show-description">
		<%= link_to 'Delete CV',  resume_path(@resume), id: "cv-link", method: :delete, data: { confirm: 'Are you sure you want to delete this CV?' } %>
	</div>
<% else %>
	<div class = "image-show-description">
		<%= link_to 'Add CV', new_resume_path, id: "cv-link" %>
	</div>
	
<% end %> 

app/views/resumes/new.html.erb
<% provide(:title, 'New') %>

<h1 class = 'research-title'>Add CV</h1>
<%= render partial: 'form' %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<div class = "about-container">
	<div class = "about-background">
		
	</div>
	<h5 class = "about-credit">Photos courtesy of Keenan Hursh and Liam Brozik.</h5>
	<div class = "about-text">
		<p>David, 19, is a Boulder, CO native who enjoys climbing, hiking and skiing in the high alpine. He is a recent Seattle, WA transplant where he attends the University of Washington and is pursuing degrees in Atmospheric Science and Applied Mathematics. His art mainly pertains to mountain landscapes that are inspired by the delicacies of the alpine environments and intricate patterns of untouched landscapes. </p>
		<br>
		<p>Feel free to contact him about any commissions, for sale items, or questions pertaining to his art.</p>
		<p>Email: <a href="mailto:bonan.dave@gmail.com">bonan.dave@gmail.com</a></p>
	</div>
	
</div>

app/views/static_pages/edit.html.erb
<div class = "research-description">
	<p id = "research-headings">Add/Delete CV</p>
	<p><%= link_to "Link", resumes_path %></p>
</div>

<div class = "research-description">
	<p id = "research-headings">Add Artwork</p>
	<p><%= link_to "Link", new_portfolio_path %></p>
</div>

<% if @interests.count > 0 %> <!-- if research exits -->
<div class = "research-description">
	<p id = "research-headings">Add/Edit Science Section</p>
	<p><%= link_to "Link", edit_interest_path(@interest), data: { 'no-turbolink'=>true}  %></p>
</div>
<% else %>
<div class = "research-description">
	<p id = "research-headings">Add/Edit Science Section</p>
	<p><%= link_to "Link", new_interest_path, data: { 'no-turbolink'=>true}  %></p>
</div>
<% end %>

<% if @backgrounds.count > 0 %> <!-- if background exits -->
<div class = "research-description">
	<p id = "research-headings">Add/Edit About Section</p>
	<p><%= link_to "Link", edit_background_path(@background), data: { 'no-turbolink'=>true}  %></p>
</div>
<% else %>
<div class = "research-description">
	<p id = "research-headings">Add/Edit About Section</p>
	<p><%= link_to "Link", new_background_path, data: { 'no-turbolink'=>true}  %></p>
</div>
<% end %>

<div class = "research-description">
	<p id = "research-headings">Add/Edit Outreach Document</p>
	<p><%= link_to "Link", editresources_path %></p>
</div>

app/views/static_pages/editresources.html.erb
<div class = "research-description">
	<p id = "research-headings">Add Resource</p>
	<p><%= link_to "New", new_resource_path %></p>
</div>

<div class = "research-description">
	<p id = "research-headings">Edit/Delete Resource</p>
	<% for doc in @resources do %>
		<p><%= doc.title %> — <%= link_to "Edit", edit_resource_path(doc) %> / <%= link_to 'Delete',  resource_path(doc), method: :delete, data: { confirm: 'Are you sure you want to delete this resource?' } %></p>
	<% end %>
</div>

app/views/static_pages/freelance.html.erb
<% provide(:title, 'Freelance Work') %>
<%= render partial: 'layouts/artheader' %>
<div class = "portfolio-container">
<% for art in @freelance do %>
	<%= link_to (portfolio_path(art)) do %>
		<div class = "image-block" style="background-image: url('<%= art.image_url(:thumb) %>');">
			<div class = "index-text">
				<h1 class = "index-title"><%= art.title %></h1>
				<div class = "index-divider"></div>
				<p class = "description-preview"><%= truncate(art.description, length: 80, separator: ' ', :escape => false) %></p>
				<div class = "arrow"></div>
			</div>
		</div>
	<% end %>
<% end %>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>

<div class = "home-container">
	<div class = "home-background">

	</div>

</div>

app/views/static_pages/shop.html.erb
<% provide(:title, 'Shop') %>
<%= render partial: 'layouts/artheader' %>
<div class = "portfolio-container">
<% for art in @sales do %>
	<%= link_to (portfolio_path(art)) do %>
		<div class = "image-block" style="background-image: url('<%= art.image_url(:thumb) %>');">
			<div class = "index-text">
				<h1 class = "index-title"><%= art.title %></h1>
				<div class = "index-divider"></div>
				<p class = "description-preview"><%= truncate(art.description, length: 80, separator: ' ', :escape => false) %></p>
				<div class = "arrow"></div>
			</div>
		</div>
	<% end %>
<% end %>
</div>